basic:
  disablePermissions: false
  checkForUpdates: true

log:
  debugSpam: false
  anonymousMetrics: true

titles:
  useTitlesInsteadOfChat: true
  useActionBar: true
  titleFadeInTime: 20
  titleStayTime: 140
  titleFadeOutTime: 20

colors:
  infoColor: GOLD
  errorColor: RED

disabledCommands:
  header:
    - '&6&l[!]&r &6Blocked Commands:'
    - ''
  concat: ' &8- &f'
  footer:
    - '&8&l> &8----- &8&l<'

chunks:
  maxChunksClaimed: 50
  particlesWhenClaiming: true
  chunkOutlineParticle: 'SMOKE_LARGE'
  allowChunkGive: true
  hideAlertsForVanishedPlayers: true
  automaticUnclaimSeconds: -1
  unclaimCheckIntervalTicks: 1200
  displayNameOfOwner: true
  defaultSendAlertsToOwner: true
  maxPerListPage: 5
  disabledWorlds: []
  disabledBlockedCommands: ["home", "rtp", "spawn"]

protection:
  blockUnclaimedChunks: false
  blockPlayerChanges: true
  blockInteractions: true
  blockTnt: true
  blockCreeper: true
  blockWither: true
  blockFireSpread: false
  blockFluidSpreadIntoClaims: false
  blockPistonsIntoClaims: false
  protectEntities: true
  blockPvp: false
  blockedCmds: []
  disableOfflineProtect: false

worldguard:
  allowClaimsInRegionsByDefault: true
  allowClaimingInNonGuardedWorlds: true
  allowAdminOverride: true

economy:
  useEconomy: true
  claimPrice: 100.0
  unclaimReward: 10.0
  firstFreeChunks: 0

data:
  saveDataInterval: 5
  keepJsonBackups: true

database:
  useDatabase: false
  groupRequests: true
  convertOldData: true
  hostname: '127.0.0.1'
  port: 3306
  database: 'MyServer'
  username: 'root'
  password: 'root'
  printDebug: false
